version: "3.8"

services:
  caddy:
    image: caddy:2.7-alpine
    container_name: caddy
    ports:
      - "8082:80"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - geth
    networks:
      - geth-network
      - blockscout-network
  sc-deployer:
    image: ghcr.io/foundry-rs/foundry:latest
    platform: linux/amd64
    container_name: sc-deployer
    user: root
    volumes:
      - ./sc-deployer:/workspace
      - ./geth-init:/shared
    working_dir: /workspace
    entrypoint: ["/bin/sh", "/workspace/entrypoint.sh"]
    depends_on:
      - geth
    networks:
      - geth-network
  sc-deployment-server:
    image: caddy:2.7-alpine
    container_name: sc-deployment-server
    ports:
      - "8081:80"
    volumes:
      - ./sc-deployment-server/Caddyfile:/etc/caddy/Caddyfile
      # serve deployment.json
      - ./sc-deployer:/usr/share/caddy
    depends_on:
      - sc-deployer
    networks:
      - geth-network
  geth:
    image: ethereum/client-go:v1.15.0
    container_name: geth
    ports:
      - "8545:8545"  # HTTP RPC
      - "8546:8546"  # WebSocket RPC
      - "30303:30303"  # P2P
      - "30303:30303/udp"  # P2P UDP
    volumes:
      - geth-data:/root/.ethereum
      - ./geth:/geth
    command: >
      --dev
      --datadir /root/.ethereum
      --http
      --http.addr 0.0.0.0
      --http.port 8545
      --http.corsdomain "*"
      --http.vhosts "*"
      --http.api "eth,net,web3,personal,miner,admin,debug"
      --ws
      --ws.addr 0.0.0.0
      --ws.port 8546
      --ws.api "eth,net,web3,personal,miner,admin,debug"
      --ws.origins "*"
      --allow-insecure-unlock
      --mine
      --networkid 1337
      --nodiscover
      --verbosity 3
      --miner.gaslimit 8000000
    restart: unless-stopped
    networks:
      - geth-network
  geth-init:
    image: ethereum/client-go:v1.15.0
    container_name: geth-init
    volumes:
      - ./geth-init:/scripts
      - geth-data:/root/.ethereum
      - ./geth-init:/shared
    entrypoint: ["/bin/sh", "/scripts/entrypoint.sh"]
    depends_on:
      - geth
    networks:
      - geth-network
  # Blockscout removed - using ngrok for external access instead

  # Graph Stack
  graph-ipfs:
    image: ipfs/go-ipfs:v0.24.0
    container_name: graph-ipfs
    ports:
      - "5001:5001"
      - "4001:4001"
    environment:
      IPFS_PROFILE: server
    volumes:
      - graph-ipfs-data:/data/ipfs
    networks:
      - geth-network

  graph-postgres:
    image: postgres:15-alpine
    container_name: graph-postgres
    environment:
      POSTGRES_DB: graph_node
      POSTGRES_USER: graph-node
      POSTGRES_PASSWORD: let-me-in
      POSTGRES_INITDB_ARGS: "--locale=C --encoding=UTF8"
    volumes:
      - graph-postgres-data:/var/lib/postgresql/data
    networks:
      - geth-network

  graph-redis:
    image: redis:7-alpine
    container_name: graph-redis
    networks:
      - geth-network

  graph-node:
    image: graphprotocol/graph-node:v0.35.0
    container_name: graph-node
    environment:
      postgres_host: graph-postgres
      postgres_user: graph-node
      postgres_pass: let-me-in
      postgres_db: graph_node
      ipfs: graph-ipfs:5001
      ethereum: 'geth:http://geth:8545'
      GRAPH_LOG: info
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8020:8020"
      - "8030:8030"
      - "8040:8040"
    depends_on:
      - graph-ipfs
      - graph-postgres
      - graph-redis
      - geth
    networks:
      - geth-network

volumes:
  geth-data:
  graph-ipfs-data:
  graph-postgres-data:

networks:
  geth-network:
    driver: bridge
  blockscout-network:
    external: true
    name: docker-compose_default